export const UPDATE_DATA_FROM_SERVICE = 'UPDATE_DATA_FROM_SERVICE';
export const SERVICE_DATA_CHANGED_UP = 'SERVICE_DATA_CHANGED_UP';
export const SERVICE_DATA_CHANGED_DOWN = 'SERVICE_DATA_CHANGED_DOWN';
