export const SET_FETCH_INTERVAL = 'SET_FETCH_INTERVAL';
export const CONNECTION_SOCKET = 'CONNECTION_SOCKET';
export const CONNECTION_SOCKET_SUCCESS = 'CONNECTION_SOCKET_SUCCESS';
export const CONNECTION_SOCKET_FAILURE = 'CONNECTION_SOCKET_FAILURE';

