const actionTypes = {};

actionTypes.CONNECTION_INIT = 'CONNECTION_INIT';
actionTypes.STREAM_SERVER_CONNECT = 'STREAM_SERVER_CONNECT';
actionTypes.STREAM_SERVER_DISCONNECT = 'STREAM_SERVER_DISCONNECT';
actionTypes.UPDATE_QUOTES = 'UPDATE_QUOTES';
actionTypes.TOGGLE_TICKER = 'TOGGLE_TICKER';
actionTypes.APPLY_SORT_PARAMS = 'APPLY_SORT_PARAMS';
actionTypes.SET_HISTORY_LENGTH = 'SET_HISTORY_LENGTH';

export default actionTypes;